[INFO   ] Logger: Record log in /storage/emulated/0/python3/Kivy/Api Android/Plyer/Gps/.kivy/logs/kivy_21-04-28_11.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.8.3 (default, Jun 15 2020, 02:19:10) 
[GCC 9.3.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/python3/Kivy/Api Android/Plyer/Gps/main.py", line 4, in <module>
[WARNING] stderr:     class Roda(App):
[WARNING] stderr:   File "/storage/emulated/0/python3/Kivy/Api Android/Plyer/Gps/main.py", line 5, in Roda
[WARNING] stderr:     conf=gps.configure(on_location=on_gps_location)
[WARNING] stderr: NameError: name 'on_gps_location' is not defined
